### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by statquant** [fastverse/fastverse#18]
Hello, I wanted to suggest packages additions and removals 
- [nanotime ](https://github.com/eddelbuettel/nanotime) is the first package to handle nanos in R, I think it should be used in replacement of clock
- [clustermq ](https://github.com/mschubert/clustermq) is a package that leverage zeromq to send function to workers on a grid with 0 files involved
- [qs](https://github.com/traversc/qs) is a binary format like fst that supports all objects (vs data.frames for fst) though no random access
- lubridate is (I think) fairly slow so I am surprised it’s on the list

Many thanks for this universe, I did not know kit, that's great to discover new packages
Regards

**Comment by SebKrantz** [comment]
Hello, thank you! I already considered nanotime, but did not include it for now because my thinking was it provides a specialized class that few people require and those that require it know about it. But I can include it for sure. Lubridate and ggplot2 are on the list because I haven’t quite found convenient replacements for them, and the fastverse should still be somewhat well rounded. I don’t know about the other packages, but you can send a pull request to     the development branch, making a new category for reading and writing files.

**Comment by SebKrantz** [comment]
Great, thanks! So what do you use for standard Date and POSIXct manipulation? I know clock does it, but is mostly geared towards its own set of classes.

**Comment by nickforr** [comment]
Hope nobody minds me jumping into this issue but is it worth mentioning the `arrow` package alongside `fst` and `qs`, as the parquet format gives options for sharing binary files with python etc (apologies if `fst` does this and I’ve missed that)?

**Comment by SebKrantz** [comment]
Thanks @nickforr, as I said a category for reading and writing files can be added featuring arrow, vroom etc. just make PR to development branch. Also mention the number of dependencies, you can use `fastverse_deps(pck, recursive = TRUE)`. 

@statquant I know about and have mentioned IDdate, but it’s a data.table thing that is not totally portable. As an economist I deal a lot with monthly and quarterly data where I use a mix of lubridate and xts/zoo. We can keep this thread open, I definitely don’t mind good packages like nanotime being addeed. I‘m not yet convinced lubridate should be removed. I also gave not reallbenckmarked it tbh, just know that dependency wise it is definitely different from the rest of the tidyverse and it serves a lot of comon tasks.

**Comment by SebKrantz** [comment]
Just one note to both of you: you need to fork, implement, and send PR on the development branch. You cannot fork "main" or "CRAN-Version" branch and send an PR from those to development, as that will include other stuff I don't want in development.

**Comment by SebKrantz** [comment]
I've added nanotime qs and arrow for now, but perhaps you can still improve on my descrriptions and add the links - as you find time.

**Comment by eddelbuettel** [comment]
(Came here late via the commit you just made.... thanks for that)

> So what do you use for standard Date and POSIXct manipulation? 

`anytime::anydate()` and `anytime::anytime()` really do all I need or want, and never need a format (on sane inputs).  Others are slowly copying its design---I need to check _when_ base R did this but it now also 'guesses' over two or three plausible formats on some converters.  And `lubridate`, apparently, also does (or will).  But like @statquant I never found a use for `lubridate`, likely because it first started it was very slow.  The C++ rewrites and pruning of dependencies made it better.

And `nanotime` is good when you have to deal with sub-microsecond timestamp as is now common with high-frequency trading data.  It's S4 class is pretty sane (thanks to @lsilvest who rewrote my more basic S3 class and then added _a ton_ more useful features). So yes, adding it here makes sense even it (sadly) is not quite as minimal in its dependencies.  At least recursively it still doesn't blow up.  I haven't looked at `clock` at all as we covered the same ground earlier for our needs so :man_shrugging:

**Comment by BenoitLondon** [comment]
Hello!
This "package" is a nice idea,  I used myself the (defunct?) [pkgverse](https://github.com/mkearney/pkgverse) package to build my own package universe...
Sorry to bump on this issue but I wanted to suggest some packages.
Maybe they are too specialized or do not meet your coding standards...

-  [speedglm](https://cran.r-project.org/web/packages/speedglm/index.html)
-  [future](https://github.com/HenrikBengtsson/future)
-  [ranger](https://github.com/imbs-hl/ranger)
-  [stringdist](https://github.com/markvanderloo/stringdist)
-  [redux](https://github.com/richfitz/redux)

**Comment by SebKrantz** [comment]
Thanks @eddelbuettel for clarifying this about `lubridate` and `nanotime`. I think it is good then to have all these packages here. I recall from my use that I didn't find `lubridate` terribly slow, and indeed it has both C and C++ functions. 

Thanks also @BenoitLondon for these suggestions. I did not know about `pkgverse`, but it's a nice idea. I could create a function `fastverse_child()` allowing the creation of a 0-dependency extensible verse like the `fastverse` - for a future release. 

Regarding the packages you suggested, I am happy to add `stringdist`. 

The others I think don't qualify because (1) `speedglm` and `ranger` are packages to estimate specific kinds of statistical models. The `fastverse` focuses on general purpose statistical computing and data manipulation, and for good reason: we are talking about more than 50 packages in the estiamtion category: from verious fast lm's, glm's, panel-data and time series models (e.g. Kalman Filter), various fast machine learning models (random forests hast at least two faster implementations, there are several fast knn and other classifiers).  We could add an "Estimation" category as an extra feature at the end of the README file, but then we should try to be comprehensive and also need to move in broad strokes e.g. just listing the packages under serveal categories liner models, time-series, classifiers, imputation etc. At the moment I certainly don't have time to ckeck out all those packages and determine their dependencies, but if you want to undertake a comprehensive mapping of fast and low-dependency estimation packages I can add it to the README. Just picking out two packages here is definitely not an option, and estimation packages will never be added to the documentation under `?fastverse_extend`. 

`future` also for me does not qualify because it is a parallel computing package. Parallel implementation alone makes nothing fast, it depends on the code that is being parallelized, and C/C++ level parallelism (as you have in `data.table`, `fst`, `roll` etc.) does a significantly better job at that. In any case, the `fastverse` includes packages alllowing you to write 'fast code' for statistical computing and data manipulation. Everything else is for the "High-Performance Computing" Task View on CRAN. `redux` appears to be in the same category, although I don't fully understand it.

**Comment by SebKrantz** [comment]
Now added `stringdist` and the links.

**Comment by BenoitLondon** [comment]
thanks! Yeah I think the ability to create several our own *-verses is quite nice, depending on what you re working on. 

some examples :
-  data-verse (which could be fastverse)
-  web-verse (with httr, rvest etc)
-  pkg-dev-verse (with testing pkg, usethis etc)
-  ML-verse (with ranger speedglm h2o etc)

Can create a new issue for this if you want?

**Comment by SebKrantz** [comment]
Thank you, yes I can add it as an extra, but the purpose of my package is not to make a verse-creating package, but to emphasize packages with certain desirable properties. Full flexibility to customize this verse, both gloablly and for specific projects, has already been granted (see vignette). The disadvantage of creating wholly separate verses is that it requires creating a source package which is not available on CRAN, whereas simply adding a configuration file inside a project directory is much easier. So I'll keep it in the back of my head and implement it if feasable. I don't think an extra issue is necessary. Thanks.

**Comment by BenoitLondon** [comment]
sure, makes sense thanks!

**Comment by SebKrantz** [comment]
So @BenoitLondon I have just pushed an update to github which includes a function `fastverse_child` that does what you want. Feel free to check it out and give feedback.

**Comment by SebKrantz** [comment]
Thanks @emmansh, this package is interesting. I will check it out.

**Comment by s3alfisc** [comment]
Hi @SebKrantz, mabye this is out of scope for the `fastverse`, but I wanted to point you towards the [dqrng](https://github.com/daqana/dqrng) package, which provides **very** fast sampling of random numbers. Here is a benchmark I did a while back: 

```
library(dqrng)
library(bench)

m <- 1000
n <- 99999
all <- m * n
bm <- bench::mark(samp = sample(x = c(1, -1), size = all, replace = TRUE),
                  dqsamp = dqsample(x = c(1,-1), size = all, replace = TRUE),
                  check = FALSE, 
                  iterations = 3)
bm

# # A tibble: 2 x 13
#   expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time
#   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm>
# 1 samp          6.37s    6.59s     0.153    1.12GB    0.153     3     3     19.56s
# 2 dqsamp        1.07s    1.43s     0.723    1.12GB    0.482     3     2      4.15s
# # ... with 4 more variables: result <list>, memory <list>, time <list>, gc <list>
```

**Comment by SebKrantz** [comment]
Thanks @s3alfisc, yes, random number generation is part of general purpose statistical computing and I am happy to include it.

**Comment by s3alfisc** [comment]
Cool that you are going to add `dqrng`, @SebKrantz!

 I have another note - I believe that the `fastDummies` package is actually **much** slower than using base R functions. I believe the main reason that it's called `fastDummies` is that it preceeded the `dummies` package and was likely faster than it :) [Here are some benchmarks from stackoverflow](https://stackoverflow.com/questions/72116844/what-is-the-fastest-way-to-generate-dummy-variables-in-r/72117155#72117155). In general, I wonder if it would be of value to create a package with an API similar to `fastDummies` that internally runs combinations of `model.matrix()` and `model.frame()` to create dummies?

**Comment by t-wojciech** [comment]
Here is a new package [ast2ast](https://github.com/Konrad1991/ast2ast) that translates some functions from R to C++, so they are faster. I think it's worth looking into.

**Comment by SebKrantz** [comment]
Thanks @t-wojciech. I also recently became aware of several approaches of compiling R to make it faster. I'll investigate and think about featuring such packages in the fastverse over the coming weeks.

**Comment by t-wojciech** [comment]
[rpolars](https://github.com/pola-rs/r-polars) bindings to Polars. It's still in the early stages (not available on CRAN), but it promises to be interesting.

**Comment by tony-aw** [comment]
> Hello, thank you! I already considered nanotime, but did not include it for now because my thinking was it provides a specialized class that few people require and those that require it know about it. But I can include it for sure. Lubridate and ggplot2 are on the list because I haven’t quite found convenient replacements for them, and the fastverse should still be somewhat well rounded. I don’t know about the other packages, but you can send a pull request to the development branch, making a new category for reading and writing files.
> 
> Otherwise I’ll look at them during the weekend...

Sorry to jump in like this. But regarding an alternative to ggplot2: what do you think of the `vegabrite` R package (https://github.com/vegawidget/vegabrite)? It looks promising (but it's still somewhat experimental).

**Comment by SebKrantz** [comment]
Thanks, its interesting indeed, especially for interactive visualization in R. However, it imports `vegawidget`, and through that incurs 34 dependencies. So given that this is experimental and with high dependency count, not really a *fastverse* candicate. But I agree with you, a lightweight and more performant system for complex graphics in R would be very nice.

**Comment by tony-aw** [comment]
Hi, thank you for your response.
Yes, including recursive dependencies the number is indeed high. Mostly due to the recursive dependencies of dependency `htmlwidgets`. If only that package could reduce its dependencies....

**Comment by tony-aw** [comment]
By the way, `stringr` has 7 dependencies, not 3:
`cli, glue (≥ 1.6.1), lifecycle (≥ 1.0.3), magrittr, rlang (≥ 1.0.0), stringi (≥ 1.5.3), vctrs`.
Why would `stringr` be in the list, considering it's just a wrapper around `stringi` thouggh with unnecessary many dependencies?

**Comment by SebKrantz** [comment]
Agreed, it could be removed, I sometimes still use it because of the more convenient API.

**Comment by waynelapierre** [comment]
Some suggestions:
1. remove magrittr. it is slow and obsolete: https://michaelbarrowman.co.uk/post/the-new-base-pipe/
2. nowadays very few R users resort to Java for speed
3. it makes no sense to resort to Julia for speed as it is slow and bloated
4. many packages are just wrappers of the real fast ones (stringr to stringi, tidytable to data.table). since this repo is called fastverse not tidyverse, you might want to only keep the real fast ones to be more focused.

**Comment by SebKrantz** [comment]
Thanks, I have adjusted the README a bit, putting *stringr*, *snakecase* and *lubridate* into the notes below each section. I want to keep *magrittr* due to the reasons mentioned [here](https://github.com/fastverse/fastverse/issues/61). Bindings to faster languages and *data.table* wrappers were moved to the end of the README.

**Comment by SebKrantz** [comment]
We will continue this thread [under Discussions](ttps://github.com/fastverse/fastverse/discussions/109). Thanks for all your input!
